### PR TITLE
Updated photo nijssen - cause I'm so vain

### PR DESCRIPTION
**Pull request by bartnijssen**
As the subject says!

### CODE REVIEW

**Comment by andywood** [comment]
did this go through proper repo-level review?

**Comment by julievano** [comment]
I checked and merged it.  Is there more that needs to be done than that??  

Julie Vano
Research Applications Laboratory
National Center for Atmospheric Research
https://ral.ucar.edu https://ral.ucar.edu/

**Comment by andywood** [comment]
I mean, c'mon, you have to make sure that Bart's new picture is showing his
good side, the lighting is right, his gaze appears steely, and the set of
his chin exudes confidence and resolve.  And check that he's not wearing an
inappropriate Hawaiian shirt (
http://www.latimes.com/opinion/opinion-la/la-ol-shirtstorm-rosetta-scientist-matt-taylor-shirt-20141118-story.html).
In this political climate we need to avoid any shirt-storms.

**Comment by julievano** [comment]
Excellent points!! I'll put together a team to start evaluating these things.

**Comment by andywood** [comment]
ha ha :) - actually now I'm worried because I don't think I have any
picture that passes all those tests.

**Comment by julievano** [comment]
Well, thankfully, I think we all will pass the appropriate Hawaiian shirt test. :o)

Have a nice weekend!

**Pull request merged**
